---
# Bad ansible! Still bad, but hopefully refactored for a bit of success - fjaspe

- name: Three Tier App Configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  pre-tasks:  
    - name: enable repos
      template:
        src: /etc/yum.repos.d/open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo
        mode: u=rw,go=r

  roles:
    - haproxy
    - tomcat
    - postgres
    - apache
